# Generated by Django 6.1 on 2026-09-02 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_stafftask'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_groups', to='tracker.member'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('loan_officer', 'Loan Officer'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('chairman', 'Chairman'), ('employee', 'Employee'), ('admin', 'Administrator')], default='employee', max_length=30),
        ),
    ]
