# Generated by Django 6.1 on 2026-09-06 13:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_fix_interest_codes_and_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.80'), max_digits=5, verbose_name='Interest rate (% per month)'),
        ),
    ]
